@startuml

title Create Listener

hide footbox

autonumber

database Firebase
participant "PISP Server" as PISP

PISP -> Firebase: ""firebase.firestore()""\n\
  "".collection("lookups")""\n\
  "".onCreate( ... )""
return ""200 OK""

@enduml
