box "Mobile Device"
  actor Alice
  participant "PISP App" as App
end box
box "PISP"
  participant "PISP Server" as Server
end box
box "Mojaloop"
  participant "Third-party\nAPI Adapter" as Adapter
end box
