@startuml Unlinking

title: Unlinking

hide footbox

box "Mobile Device"
  actor Alice
  participant "PISP App" as App
end box
box "PISP"
  participant "PISP Server" as Server
end box
box "Mojaloop"
  participant "Third-party\nAPI Adapter" as Adapter
end box

'start flow
Alice -> App++: I want to unlink this bank account

App -> Server ++: ""**DELETE /consents/{ID}**""
App <-- Server: ""**HTTP 202** (Accepted)""
deactivate App

Server -> Adapter ++: ""**DELETE /consents/{ID}**""
Adapter <-- Server: ""**HTTP 202** (Accepted)""
deactivate Server

Adapter -> Server++: ""**DELETE /consents/{ID}**""
Adapter <-- Server: ""**HTTP 200** (OK)""
deactivate Adapter

Server -> App: The account has been unlinked.
deactivate Server

@enduml
