@startuml

title Confirm Payee

hide footbox

autonumber

box "Mobile Device" #Light
  actor Alice
  participant "PISP App" as App
end box
box "PISP" #Light
  database Firebase
  participant "PISP Server" as Server
end box
box "Mojaloop" #Light
  participant "Third-party\nAPI Adapter" as Adapter
end box

Alice -> App: The payee info is correct

rnote right of App #Light
  ""updateDoc(""
  ""  "transactions/users/1234/<uuid>",""
  ""  {""
  ""    sourceAccountId: "bob.fspb",""
  ""    consentId: 123,""
  ""    amount: {""
  ""      amount: 20.00""
  ""      currency: "USD"""
  ""    },""
  ""    payer: {""
  ""      personalInfo: {""
  ""        complexName: {""
  ""          firstName: "Bob",""
  ""          lastName: "Beaver"""
  ""        }""
  ""      },""
  ""      partyIdInfo: {""
  ""        partyIdType: "OPAQUE",""
  ""        partyIdentifier: "bob1234",""
  ""        fspId: "fspb",""
  ""      }""
  ""    },""
  ""    status: "PAYEE_CONFIRMED"""
  ""  }""
  "")""
end rnote

App -> Firebase: Update transaction status
return ""200 OK""

rnote right of Firebase #Light
  ""event(""
  ""  "document.update",""
  ""  "transactions/users/1234/<uuid>",""
  ""  <snapshot object>""
  "")""
end rnote

Firebase -> Server ++: Notify update on transaction status
Firebase <-- Server: ""200 OK""

rnote right of Server #Light 
  ""**POST /thirdpartyRequests/transactions**""
  ""FSPIOP-Source: ...""
  ""FSPIOP-Destination: ...""
  ""{""
  ""  "transactionRequestId": "456",""
  ""  "sourceAccountId": "bob.fspb",""
  ""  "consentId": "789",""
  ""  "payee": {""
  ""    "partyIdInfo": {""
  ""      "partyIdType": "MSISDN",""
  ""      "partyIdentifier": "+1-222-222-2222",""
  ""      "fspId": "fspa"""
  ""    }""
  ""  },""
  ""  "payer": {""
  ""    "personalInfo": {""
  ""      "complexName": {""
  ""        "firstName": "Bob",""
  ""        "lastName": "Beaver"""
  ""      }""
  ""    },""
  ""    "partyIdInfo": {""
  ""      "partyIdType": "OPAQUE",""
  ""      "partyIdentifier": "bob1234",""
  ""      "fspId": "fspb"""
  ""    }""
  ""  },""
  ""  "amountType": "SEND",""
  ""  "amount": {,""
  ""    "amount": "20",""
  ""    "currency": "USD"""
  ""  },""
  ""  "transactionType": {""
  ""    "scenario": "TRANSFER",""
  ""    "initiator": "PAYER",""
  ""    "initiatorType": "CONSUMER"""
  ""  },""
  ""  expiration: "2020-07-15T22:17:28.985-01:00"""
  ""}""
end rnote

Server -> Adapter ++: ""**POST /thirdpartyRequests/transactions**""
Server <-- Adapter: ""**HTTP 202** (Accepted)""

rnote left of Server #Light
  ""createDoc(""
  ""  "transactionRequests/<id>",""
  ""  {""
  ""    userId: 1234,""
  ""    key: <uuid>""
  ""  }""
  "")""
end rnote

Server -> Firebase: Create mapping between\nuser info and transactionRequestId
Server <-- Firebase: ""200 OK""
deactivate Server

...

note over Alice, Adapter
  Transaction processes happen in Mojaloop (validation and quoting).
end note

...

@enduml
