@startuml

title Authorize Transaction

hide footbox

autonumber

box "Mobile Device" #Light
  actor Alice
  participant "PISP App" as App
end box
box "PISP" #Light
  database Firebase
  participant "PISP Server" as Server
end box
box "Mojaloop" #Light
  participant "Switch" as Mojaloop
end box

Alice -> App: Authorize the transaction

rnote right of App #Light
  ""firebase.firestore()""
  ""  .collection("transactions")""
  ""  .doc("456")""
  ""  .set({""
  ""    authenticationValue: {""
  ""      pinValue: "base64(xxx)",""
  ""      counter: "1"""
  ""    },""
  ""    status: "AUTHORIZED"""
  ""  }, { merge: true })""
end rnote

App -> Firebase: Update transaction status
return ""200 OK""

rnote right of Firebase #Light
  ""event(""
  ""  "document.update",""
  ""  "transactions/456",""
  ""  <snapshot object>""
  "")""
end rnote

Firebase -> Server ++: Notify update on transaction status
Firebase <-- Server: ""200 OK""

rnote right of Server #Light
  ""**PUT /authorizations/456**""
  ""FSPIOP-Source: pisp""
  ""FSPIOP-Destination: fspb""
  ""{""
  ""  authentication: "U2F",""
  ""  authenticationValue: {""
  ""    pinValue: "base64(xxx)",""
  ""    counter: "1"""
  ""  },""
  ""}""
end rnote

Server -> Mojaloop ++: ""**PUT /authorizations/456**""
Server <-- Mojaloop: ""200 OK""
deactivate Server

...

note over Alice, Mojaloop
  Transaction is processed if the user provides a valid authorization.
end note

...

@enduml
