@startuml

title Authorize Transaction

autonumber

box "Mobile Device" #Light
  actor Alice
  participant "PISP App" as App
end box
box "PISP" #Light
  database Firebase
  participant "PISP Server" as Server
end box
box "Mojaloop" #Light
  participant "Third-party\nAPI Adapter" as Adapter
end box

Alice -> App: Authorize the transaction

rnote right of App #Light
  ""updateDoc(""
  ""  "transactions/users/1234/<uuid>",""
  ""  {""
  ""    authorizationInfo: {""
  ""      authentication: enum,""
  ""      authenticationValue: string""
  ""    },""
  ""    status: "AUTHORIZED"""
  ""  }""
  "")""
end rnote

App -> Firebase: Update transaction status
return ""200 OK""

rnote right of Firebase #Light
  ""event(""
  ""  "document.update",""
  ""  "transactions/users/1234/<uuid>",""
  ""  {""
  ""    authorizationInfo: {""
  ""      authentication: enum,""
  ""      authenticationValue: string""
  ""    },""
  ""    status: "AUTHORIZED"""
  ""  }""
  "")""
end rnote

Firebase -> Server: Notify update on transaction status
return ""200 OK""

rnote right of Server #Light
  ""**PUT /authorizations/{ID}**""
  ""FSPIOP-Source: ...""
  ""FSPIOP-Destination: ...""
  ""{""
  ""  "authenticationInfo": {""
  ""    "authentication": enum,""
  ""    "authenticationValue": string   // diff pisp docs""
  ""  },""
  ""  "responseType": string""
  ""}""
end rnote

Server -> Adapter ++: ""**PUT /authorizations/{ID}**""
Server <-- Adapter: ""**HTTP 200** (OK)""
deactivate Server

...

note over Alice, Adapter
  Transaction is processed if the user provides a valid authorization.
end note

...

rnote left of Adapter #Light
  ""**PUT /thirdpartyRequests/transactions/{ID}**""
  ""FSPIOP-Source: ...""
  ""FSPIOP-Destination: ...""
  ""{""
  ""  "transactionId": string,""
  ""  "transactionRequestState": enum""
  ""}""
end rnote

Adapter -> Server ++: ""**PUT /thirdpartyRequests/transactions/{ID}**""
Adapter <-- Server: ""**HTTP 200** (OK)""
deactivate Adapter

rnote left of Server #Light
  ""updateDoc(""
  ""  "/transactions/users/1234/<uuid>",""
  ""  {""
  ""    status: "SUCCESS"""
  ""  }""
  "")""
end rnote

Server -> Firebase: Update transaction status
return ""200 OK""

rnote left of Firebase #Light
  ""event(""
  ""  "document.update",""
  ""  "/transactions/users/1234/<uuid>",""
  ""  {""
  ""    status: "SUCCESS"""
  ""  }""
  "")""
end rnote

Firebase -> App: Notify on transaction status update
return ""200 OK""

App -> Alice: Transaction success

@enduml
