@startuml

title Authorize Transaction

hide footbox

autonumber

box "Mobile Device" #Light
  actor Alice
  participant "PISP App" as App
end box
box "PISP" #Light
  database Firebase
  participant "PISP Server" as Server
end box
box "Mojaloop" #Light
  participant "Third-party\nAPI Adapter" as Adapter
end box

activate Adapter

rnote left of Adapter #Light
  ""**PUT /thirdpartyRequests/transactions/{ID}**""
  ""FSPIOP-Source: ...""
  ""FSPIOP-Destination: ...""
  ""{""
  ""  "transactionId": "901",""
  ""  "transactionRequestState": "ACCEPTED"""
  ""}""
end rnote

Adapter -> Server ++: ""**PUT /thirdpartyRequests/transactions/{ID}**""
Adapter <-- Server: ""**HTTP 200** (OK)""
deactivate Adapter


rnote left of Server #Light
  ""getDoc(""
  ""  "transactionRequests/<id>"""
  "")""
end rnote

Server -> Firebase: Get mapping to user info

rnote right of Firebase #Light
  ""value({""
  ""  userId: 1234,""
  ""  key: <uuid>""
  ""})""
end rnote

Server <-- Firebase: Return user info for\nthe transaction request

rnote left of Server #Light
  ""updateDoc(""
  ""  "/transactions/users/1234/<uuid>",""
  ""  {""
  ""    status: "SUCCESS"""
  ""  }""
  "")""
end rnote

Server -> Firebase: Update transaction status
Server <-- Firebase: ""200 OK""

deactivate Server

rnote left of Firebase #Light
  ""event(""
  ""  "document.update",""
  ""  "/transactions/users/1234/<uuid>",""
  ""  {""
  ""    status: "SUCCESS"""
  ""  }""
  "")""
end rnote

Firebase -> App: Notify on transaction status update
return ""200 OK""

App -> Alice: Transaction success

@enduml
