@startuml

title Transaction Feedback

hide footbox

autonumber

box "Mobile Device" #Light
  actor Alice
  participant "PISP App" as App
end box
box "PISP" #Light
  database Firebase
  participant "PISP Server" as Server
end box
box "Mojaloop" #Light
  participant "Switch" as Mojaloop
end box

activate Mojaloop

rnote left of Mojaloop #Light
  ""**PUT /thirdpartyRequests/transactions/456**""
  ""FSPIOP-Source: fspb""
  ""FSPIOP-Destination: pisp""
  ""{""
  ""  "transactionId": "901",""
  ""  "transactionRequestState": "ACCEPTED"""
  ""}""
end rnote

Mojaloop -> Server ++: ""**PUT /thirdpartyRequests/transactions/456**""
Mojaloop <-- Server: ""200 OK""
deactivate Mojaloop


rnote left of Server #Light
  ""firebase.firestore()""
  ""  .collection("transactions")""
  ""  .doc("456")""
  ""  .set({""
  ""    status: "SUCCESS"""
  ""  }, { merge: true })""
end rnote

Server -> Firebase: Update transaction status
Server <-- Firebase: ""200 OK""

deactivate Server

rnote left of Firebase #Light
  ""event(""
  ""  "document.update",""
  ""  "/transactions/456",""
  ""  <snapshot object>""
  "")""
end rnote

Firebase -> App: Notify on transaction status update
return ""200 OK""

App -> Alice: Transaction success

@enduml
