@startuml
title Create Listener

autonumber
participant App
database Firebase
participant "PISP Server" as PISP

PISP -> Firebase: ""createListener(collection='consents/')""
return ""200 OK""

App -> Firebase: ""createListener(collection='consents/users/1234')""
return ""200 OK""

@enduml
