@startuml

title: Discovery 

hide footbox

box "Mobile Device" #Light
  actor Alice
  participant "PISP App" as App
end box
box "PISP" #Light
  participant "Firebase" as Firebase
  participant "PISP Server" as Server
end box
box "Mojaloop" #Light
  participant "Switch" as Adapter
end box

' start flow
opt Update every X time interval
  Server -> Adapter: ""**GET /participants**""
  Server <-- Adapter: ""**HTTP 202** (Accepted)""

  Adapter -> Adapter: Lookup data in Mojaloop

  alt Successful
    Adapter -> Server: ""**PUT /participants**""\n\
""{ ""\n\
""  participants: [""\n\
""    {""\n\
""      "fspId": string,""\n\
""      "name": string""\n\
""    }""\n\
""  ] ""\n\
""} ""
    return ""**HTTP 200** (OK)""

    rnote left of Server #Light
      ""updateDoc(""
      ""  "/participants",""
      ""  [""
      ""    {""
      ""      fspId: "fspa",""
      ""      name: "FSP A"""
      ""    },""
      ""    {""
      ""      fspId: "fspb",""
      ""      name: "FSP B"""
      ""    }""
      ""  ]""
      "")""
    end rnote
    Server -> Firebase: Update list of participants

  else Error
    Adapter -> Server : ""**PUT /participants/error**""\n\
""{ ""\n\
""  "errorInformation": {""\n\
""    "errorCode": string,""\n\
""    "errorDescription": string,""\n\
""    "extensionList": {""\n\
""      "extension": [""\n\
""        {""\n\
""          "key": string,""\n\
""          "value": string""\n\
""        }""\n\
""      ]""\n\
""    }""\n\
""  }""\n\
""} ""

    Adapter <-- Server: ""**HTTP 200** (OK)""

    Server -> Server: Schedule retry\nwith exponential backoff
  end
end

deactivate Adapter

Alice -> App ++: Open account linking screen

rnote right of App #Light
  ""getDoc("/participants")""
end rnote

App -> Firebase ++: ""Query list of participants""

rnote left of Firebase #Light
  ""result(""
  ""  [""
  ""    {""
  ""      fspId: "fspa",""
  ""      name: "FSP A"""
  ""    },""
  ""    {""
  ""      fspId: "fspb",""
  ""      name: "FSP B"""
  ""    }""
  ""  ]""
  "")""
end rnote

return ""**HTTP 200** (OK)""

App -> Alice: Display list of available FSPs

@enduml
