@startuml

title: Consent Request

hide footbox

box "Mobile Device" #Light
  actor Alice
  participant "PISP App" as App
end box
box "PISP" #Light
  participant "Firebase" as Firebase
  participant "PISP Server" as Server
end box
box "Mojaloop" #Light
  participant "Third-party\nAPI Adapter" as Adapter
end box

' start flow

Alice -> App: Choose one of the available FSPs \nand provide identifier

rnote right of App #Light
  ""createDoc(""
  ""  "/consents/users/1234/<uuid>",""
  ""  {""
  ""    status: "REQUESTED"""
  ""  }""
  "")""
end rnote

App -> Firebase: Create consent request in database
return ""**HTTP 200** (OK)""

rnote right of Firebase #Light
  ""event(""
  ""  "document.create",""
  ""  "/consents/users/1234/<uuid>",""
  ""  {""
  ""    status: "REQUESTED"""
  ""  }""
  "")""
end rnote

Firebase -> Server: Notify update on consents collection
return ""**HTTP 200** (OK)""

deactivate App

Server -> Adapter ++: ""**POST /consentRequests**""\n\
""{""\n\
""  "id": string,""\n\
""  "initiatorId": string,""\n\
""  "authChannels": [string],""\n\
""  "scopes": [""\n\
""    {""\n\
""      "accountId": string,""\n\
""      "actions": [string]""\n\
""    }""\n\
""  ],""\n\
""  "callbackUri": string""\n\
""}""

Server <-- Adapter : ""**HTTP 202** (Accepted)""
deactivate Server

Adapter -> Server:  ""**PUT /consentRequests/{ID}**""\n\
""{""\n\
""  "initiatorId": string,""\n\
""  "authChannels": [string],   // length always 1?""\n\
""  "scopes": [""\n\
""    {""\n\
""      "accountId": string,""\n\
""      "actions": [string]""\n\
""    }""\n\
""  ],""\n\
""  "callbackUri": string,""\n\
""  "authUri": string | null    // null if OTP""\n\
""}""

Adapter <-- Server: ""**HTTP 200** (OK)""
deactivate Adapter

rnote left of Server #Light
  ""updateDoc(""
  ""  "/consents/users/1234/<uuid>",""
  ""  {""
  ""    authChannel: enum,  // "OTP" or "FIDO"""
  ""    authUri: string | null,""
  ""    status: "AUTH_REQUIRED"""
  ""  }""
  "")""
end rnote

Server -> Firebase: Update consent status
return ""200 OK""

rnote left of Firebase #Light
  ""event(""
  ""  "document.update",""
  ""  "/consents/users/1234/<uuid>",""
  ""  {""
  ""    authChannel: enum,  // "OTP" or "FIDO"""
  ""    authUri: string | null,""
  ""    status: "AUTH_REQUIRED"""
  ""  }""
  "")""
end rnote 

Firebase -> App: Notify update on consent status
return ""200 OK""

...

note over Alice, Adapter
  If the authentication method is OTP, the user will receive an OTP from the FSP.
  If the authentication method is Web, the PISP app will redirect user to the ""authUri"" provided by the FSP. 
end note

...

@enduml
