@startuml

title: Authentication (OTP)

hide footbox

box "Mobile Device" #Light
  actor Alice
  participant "PISP App" as App
end box
box "PISP" #Light
  participant "Firebase" as Firebase
  participant "PISP Server" as Server
end box
box "Mojaloop" #Light
  participant "Switch" as Mojaloop
end box

Alice -> App ++: Here is the OTP code

rnote right of App #Light
  ""{""
  ""  "initiatorId": "pisp",""
  ""  "authChannels": ["OTP"],""
  ""  "scopes": [""
  ""    { accountId: "aaa.bob.fspb",""
  ""      actions: ["accounts.transfer", "accounts.getBalance"] },""
  ""    { accountId: "bbb.bob.fspb",""
  ""      actions: ["accounts.transfer", "accounts.getBalance"] }""
  ""  ],""
  ""  "callbackUri": "pisp-app://callback...",""
  ""  "authUri": null,""
  ""  "authToken": <OTP>""
  ""}""
end rnote

App -> Server++: ""**PUT /consentRequests/111**""
App <-- Server : ""200 OK""
deactivate App

rnote right of Server #Light
  ""{""
  ""  "initiatorId": "pisp",""
  ""  "authChannels": ["OTP"],""
  ""  "scopes": [""
  ""    { accountId: "aaa.bob.fspb",""
  ""      actions: ["accounts.transfer", "accounts.getBalance"] },""
  ""    { accountId: "bbb.bob.fspb",""
  ""      actions: ["accounts.transfer", "accounts.getBalance"] }""
  ""  ],""
  ""  "callbackUri": "pisp-app://callback...",""
  ""  "authUri": null,""
  ""  "authToken": <OTP>""
  ""}""
end rnote
Server -> Mojaloop ++: ""**PUT /consentRequests/111**""

Server <-- Mojaloop: ""200 OK""
deactivate Server

@enduml
