@startuml

title: Grant Consent

hide footbox

box "Mobile Device" #Light
  actor Alice
  participant "PISP App" as App
end box
box "PISP" #Light
  participant "Firebase" as Firebase
  participant "PISP Server" as Server
end box
box "Mojaloop" #Light
  participant "Switch" as Mojaloop
end box

activate Mojaloop

Mojaloop -> Mojaloop: Validate ""authToken""

rnote left of Mojaloop #Light
  ""{""
  ""  "id": "123",""
  ""  "requestId": "111",""
  ""  "initiatorId": "pisp",""
  ""  "participantId": "fspb",""
  ""  "scopes": [""
  ""    { accountId: "aaa.bob.fspb",""
  ""      actions: ["accounts.transfer"] },""
  ""    { accountId: "bbb.bob.fspb",""
  ""      actions: ["accounts.transfer"] }""
  ""  ],""
  ""  "credential": null""
  ""}""
end rnote

Mojaloop -> Server ++: ""**POST /consents**""

Mojaloop <-- Server: ""**HTTP 202** (Accepted)""
deactivate Mojaloop

rnote left of Server #Light
  ""firebase.firestore()""
  ""  .collection("consents")""
  ""  .where("consentRequestId", "==", "111")""
  ""  .update({""
  ""    consentId: "123",""
  ""    // save the granted scopes since it might be""
  ""    // altered by the DFSP""
  ""    scopes: [""
  ""      { accountId: "aaa.bob.fspb",""
  ""        actions: ["accounts.transfer"] },""
  ""      { accountId: "bbb.bob.fspb",""
  ""        actions: ["accounts.transfer"] }""
  ""    ],""
  ""    status: "CONSENT_GRANTED"""
  ""  })""
end rnote

Server -> Firebase ++: Update consent document
Server <-- Firebase: ""200 OK""

rnote left of Firebase #Light 
  ""event(""
  ""  "document.update",""
  ""  "consents/abc123",""
  ""  <snapshot object>""
  "")""
end rnote

Firebase -> App: Notify update on consent document
deactivate Firebase

@enduml
