@startuml

title: Sign Challenge

hide footbox

box "Mobile Device" #Light
  actor Alice
  participant "PISP App" as App
end box
box "PISP" #Light
  participant "Firebase" as Firebase
  participant "PISP Server" as Server
end box
box "Mojaloop" #Light
  participant "Switch" as Mojaloop
end box

'start flow
Alice -> App ++: Give fingerprint

rnote right of App #Light
  ""firebase.firestore()""
  ""  .collection("consents")""
  ""  .where("consentId", "==", "123")""
  ""  .set({""
  ""    credential: {""
  ""      id: "12345",""
  ""      challenge: {""
  ""        signature: base64(...)""
  ""      },""
  ""      payload: base64(...)""
  ""    }""
  ""  }, { merge: true })""
end rnote

App -> Firebase ++: Update consent document
App <-- Firebase: ""200 OK""
deactivate App

rnote right of Firebase #Light
  ""event(""
  ""  "document.update",""
  ""  "consents/abc123",""
  ""  <snapshot object>""
  "")""
end rnote

Firebase -> Server ++: Notify update on consent document
Firebase <-- Server: ""200 OK""
deactivate Firebase

rnote right of Server #Light
  ""{""
  ""  "requestId": "111",""
  ""  "initiatorId": "pisp",""
  ""  "participantId": "fspb",""
  ""  "scopes": [""
  ""    { accountId: "aaa.bob.fspb",""
  ""      actions: ["accounts.transfer"] },""
  ""    { accountId: "bbb.bob.fspb",""
  ""      actions: ["accounts.transfer"] }""
  ""  ],""
  ""  "credential": {""
  ""    "id": "12345",""
  ""    "credentialType": "FIDO",""
  ""    "status": "PENDING",""
  ""    "challenge": {""
  ""      "payload": base64(...),""
  ""      "signature": base64(...)""
  ""    },""
  ""    "payload": base64(...)""
  ""  }""
  ""}""
end rnote

Server -> Mojaloop ++: ""**PUT /consents/123**""
Server <-- Mojaloop: ""202 Accepted""

deactivate Server

rnote left of Mojaloop #Light
  ""{""
  ""  "requestId": "111",""
  ""  "initiatorId": "pisp",""
  ""  "participantId": "fspb",""
  ""  "scopes": [""
  ""    { accountId: "aaa.bob.fspb",""
  ""      actions: ["accounts.transfer"] },""
  ""    { accountId: "bbb.bob.fspb",""
  ""      actions: ["accounts.transfer"] }""
  ""  ],""
  ""  "credential": {""
  ""    "id": "12345",""
  ""    "credentialType": "FIDO",""
  ""    "status": "VERIFIED",""
  ""    "challenge": {""
  ""      "payload": base64(...),""
  ""      "signature": base64(...)""
  ""    },""
  ""    "payload": base64(...)""
  ""  },""
  ""  status: "SUCCESS" // TBC""
  ""}""
end rnote

Mojaloop -> Server ++: ""**PUT /consents/123**""

Mojaloop <-- Server: ""200 OK""

rnote left of Server #Light
  ""firebase.firestore()""
  ""  .collection("consents")""
  ""  .where("consentId", "==", "123")""
  ""  .update({""
  ""    status: "CREDENTIAL_REGISTERED"""
  ""  })""
end rnote

Server -> Firebase ++: Update consent document
Server <-- Firebase: ""200 OK""
deactivate Server

rnote left of Firebase #Light
  ""event(""
  ""  "document.update",""
  ""  "consents/abc123",""
  ""  <snapshot object>""
  "")""
end rnote

Firebase -> App ++: Notify update on consent document
Firebase <-- App: ""200 OK""
deactivate Firebase

App -> Alice: You are ready to send\nmoney from your account
deactivate App

@enduml
